backend:
  name: github
  repo: chucorate/gdcs2
  branch: main
  open_authoring: true

media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow
site-url: https://www.gdcreatorschool.com/
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

fields: &page_fields
  - { label: Draft, name: draft, widget: boolean,
    hint: "Enabling draft mode lets you save your changes, but doesn't make them available on the website."}
  - { label: Title, name: title, widget: string }
  - { label: Weight, name: weight, widget: number,
    hint: "Pages with high weight will display below pages with low weight.\nLook at other guides in this folder to see where to place your own." }
  - { label: Math, name: math, widget: boolean, required: false,
    hint: "Lets you use MathJax for math formatting in your guide."}
  - { label: Body, name: body, widget: markdown }

collections:
  - name: guides
    label: Guides
    folder: "content/docs/guides"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    nested:
      depth: 5
      subfolders: false
    fields: *page_fields
    create: true

  - name: contributing
    label: Contributing
    folder: "content/contributing"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    nested:
      depth: 5
      subfolders: false
    fields: *page_fields
